/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'settled' : IDL.Null,
  'live' : IDL.Null,
});
export const EventResult = IDL.Variant({
  'pending' : IDL.Null,
  'away' : IDL.Null,
  'draw' : IDL.Null,
  'home' : IDL.Null,
});
export const SportsEventView = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : EventStatus,
  'result' : EventResult,
  'homeTeam' : IDL.Text,
  'oddsAway' : IDL.Float64,
  'oddsDraw' : IDL.Float64,
  'oddsHome' : IDL.Float64,
  'sport' : IDL.Text,
  'homeScore' : IDL.Nat,
  'awayTeam' : IDL.Text,
  'awayScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const BetResult = IDL.Variant({
  'won' : IDL.Null,
  'pending' : IDL.Null,
  'lost' : IDL.Null,
});
export const BetView = IDL.Record({
  'eventId' : IDL.Nat,
  'result' : BetResult,
  'prediction' : EventResult,
  'odds' : IDL.Float64,
  'user' : IDL.Principal,
  'stake' : IDL.Nat,
  'payout' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [
        IDL.Record({
          'startTime' : Time,
          'homeTeam' : IDL.Text,
          'oddsAway' : IDL.Float64,
          'oddsDraw' : IDL.Float64,
          'oddsHome' : IDL.Float64,
          'sport' : IDL.Text,
          'awayTeam' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllEvents' : IDL.Func([], [IDL.Vec(SportsEventView)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventsBySport' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SportsEventView)],
      ['query'],
    ),
  'getOpenBets' : IDL.Func([], [IDL.Vec(BetView)], ['query']),
  'getUserBets' : IDL.Func([], [IDL.Vec(BetView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'settleEvent' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateEventStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const EventStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'settled' : IDL.Null,
    'live' : IDL.Null,
  });
  const EventResult = IDL.Variant({
    'pending' : IDL.Null,
    'away' : IDL.Null,
    'draw' : IDL.Null,
    'home' : IDL.Null,
  });
  const SportsEventView = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : EventStatus,
    'result' : EventResult,
    'homeTeam' : IDL.Text,
    'oddsAway' : IDL.Float64,
    'oddsDraw' : IDL.Float64,
    'oddsHome' : IDL.Float64,
    'sport' : IDL.Text,
    'homeScore' : IDL.Nat,
    'awayTeam' : IDL.Text,
    'awayScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const BetResult = IDL.Variant({
    'won' : IDL.Null,
    'pending' : IDL.Null,
    'lost' : IDL.Null,
  });
  const BetView = IDL.Record({
    'eventId' : IDL.Nat,
    'result' : BetResult,
    'prediction' : EventResult,
    'odds' : IDL.Float64,
    'user' : IDL.Principal,
    'stake' : IDL.Nat,
    'payout' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [
          IDL.Record({
            'startTime' : Time,
            'homeTeam' : IDL.Text,
            'oddsAway' : IDL.Float64,
            'oddsDraw' : IDL.Float64,
            'oddsHome' : IDL.Float64,
            'sport' : IDL.Text,
            'awayTeam' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(SportsEventView)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventsBySport' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SportsEventView)],
        ['query'],
      ),
    'getOpenBets' : IDL.Func([], [IDL.Vec(BetView)], ['query']),
    'getUserBets' : IDL.Func([], [IDL.Vec(BetView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'settleEvent' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateEventStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };