/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BetResult = { 'won' : null } |
  { 'pending' : null } |
  { 'lost' : null };
export interface BetView {
  'eventId' : bigint,
  'result' : BetResult,
  'prediction' : EventResult,
  'odds' : number,
  'user' : Principal,
  'stake' : bigint,
  'payout' : bigint,
}
export type EventResult = { 'pending' : null } |
  { 'away' : null } |
  { 'draw' : null } |
  { 'home' : null };
export type EventStatus = { 'upcoming' : null } |
  { 'settled' : null } |
  { 'live' : null };
export interface SportsEventView {
  'id' : bigint,
  'startTime' : Time,
  'status' : EventStatus,
  'result' : EventResult,
  'homeTeam' : string,
  'oddsAway' : number,
  'oddsDraw' : number,
  'oddsHome' : number,
  'sport' : string,
  'homeScore' : bigint,
  'awayTeam' : string,
  'awayScore' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [
      {
        'startTime' : Time,
        'homeTeam' : string,
        'oddsAway' : number,
        'oddsDraw' : number,
        'oddsHome' : number,
        'sport' : string,
        'awayTeam' : string,
      },
    ],
    bigint
  >,
  'getAllEvents' : ActorMethod<[], Array<SportsEventView>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventsBySport' : ActorMethod<[string], Array<SportsEventView>>,
  'getOpenBets' : ActorMethod<[], Array<BetView>>,
  'getUserBets' : ActorMethod<[], Array<BetView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[bigint, string, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'settleEvent' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'updateEventStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];